// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ozvjxcazehhqrkyeqbti.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96dmp4Y2F6ZWhocXJreWVxYnRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg4NTIyNzgsImV4cCI6MjA1NDQyODI3OH0.F_f7Ce6GCuHT9F2l_yQIY5xU7ZjOGDizIThyORZXvdQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);